name: packer

on:
  push:
    branches:
      - master
      - main

jobs:
  check:

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2  

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))') 

      - name: Install NPM Dependencies
        run: Rscript -e "packer:::engine_install()"

      - name: Check minification
        run: Rscript -e "packer:::are_minified('inst')"
